### PR TITLE
Fixed generation of AccessToken from RefreshToken

### PR DESCRIPTION
**Pull request by tpazderka**

### CODE REVIEW

**Comment by rohe** [comment]
Did it slightly different !

**Comment by tpazderka** [comment]
I don't see the commit. Is it pushed yet?

**Comment by rohe** [comment]
> 11 jan 2016 kl. 14:01 skrev tpazderka <notifications@github.com>:
> 
> I don't see the commit. Is it pushed yet?

Now it is!

**Comment by tpazderka** [comment]
Thanks!

**Pull request closed without merging**
